import * as THREE from 'three';

/**
 * Color palettes for different seasons and moods
 */
export enum Season {
  SPRING = 'spring',
  SUMMER = 'summer',
  AUTUMN = 'autumn',
  WINTER = 'winter',
}

export enum Mood {
  CHILL = 'chill',
  SUNSET_GLOW = 'sunset',
  NIGHT_DRIVE = 'night',
  STORMY = 'stormy',
  VIBESCAPE = 'vibescape',
}

export interface PaletteColors {
  skyTop: THREE.Color;
  skyHorizon: THREE.Color;
  sunColor: THREE.Color;
  ambientColor: THREE.Color;
  groundColor: THREE.Color;
  roadColor: THREE.Color;
  roadLineColor: THREE.Color;
  terrainColor: THREE.Color;
  terrainColor2: THREE.Color;
  waterColor: THREE.Color;
  fogColor: THREE.Color;
  fogDensity: number;
  timeOfDay: number; // 0 = midnight, 0.5 = noon, 1 = midnight
}

export class Palette {
  private static palettes: Record<Season, Record<Mood, PaletteColors>> = {
    [Season.SPRING]: {
      [Mood.CHILL]: {
        skyTop: new THREE.Color(0x87ceeb),
        skyHorizon: new THREE.Color(0xb0e0e6),
        sunColor: new THREE.Color(0xfffacd),
        ambientColor: new THREE.Color(0xffffff),
        groundColor: new THREE.Color(0x90ee90),
        roadColor: new THREE.Color(0x505050),
        roadLineColor: new THREE.Color(0xffffff),
        terrainColor: new THREE.Color(0x7ec850),
        terrainColor2: new THREE.Color(0x90ee90),
        waterColor: new THREE.Color(0x4a90e2),
        fogColor: new THREE.Color(0xb0e0e6),
        fogDensity: 0.008,
        timeOfDay: 0.4,
      },
      [Mood.SUNSET_GLOW]: {
        skyTop: new THREE.Color(0xff6b6b),
        skyHorizon: new THREE.Color(0xffa500),
        sunColor: new THREE.Color(0xff8c42),
        ambientColor: new THREE.Color(0xffcc99),
        groundColor: new THREE.Color(0x8fbc8f),
        roadColor: new THREE.Color(0x4a4a4a),
        roadLineColor: new THREE.Color(0xffe4b5),
        terrainColor: new THREE.Color(0x6b9b37),
        terrainColor2: new THREE.Color(0x8fbc8f),
        waterColor: new THREE.Color(0xff6b6b).lerp(new THREE.Color(0x4a90e2), 0.5),
        fogColor: new THREE.Color(0xffa500),
        fogDensity: 0.012,
        timeOfDay: 0.75,
      },
      [Mood.NIGHT_DRIVE]: {
        skyTop: new THREE.Color(0x0a0e27),
        skyHorizon: new THREE.Color(0x1a1f3a),
        sunColor: new THREE.Color(0x6b8fb5),
        ambientColor: new THREE.Color(0x2a3a5a),
        groundColor: new THREE.Color(0x1a3a1a),
        roadColor: new THREE.Color(0x303030),
        roadLineColor: new THREE.Color(0x9999ff),
        terrainColor: new THREE.Color(0x2a4a2a),
        terrainColor2: new THREE.Color(0x1a3a1a),
        waterColor: new THREE.Color(0x0a2a4a),
        fogColor: new THREE.Color(0x1a1f3a),
        fogDensity: 0.015,
        timeOfDay: 0.05,
      },
      [Mood.STORMY]: {
        skyTop: new THREE.Color(0x4a5568),
        skyHorizon: new THREE.Color(0x718096),
        sunColor: new THREE.Color(0xa0aec0),
        ambientColor: new THREE.Color(0x718096),
        groundColor: new THREE.Color(0x6b7e69),
        roadColor: new THREE.Color(0x3a3a3a),
        roadLineColor: new THREE.Color(0xcccccc),
        terrainColor: new THREE.Color(0x5a7a5a),
        terrainColor2: new THREE.Color(0x6b8e6b),
        waterColor: new THREE.Color(0x4a5a6a),
        fogColor: new THREE.Color(0x718096),
        fogDensity: 0.025,
        timeOfDay: 0.45,
      },
      [Mood.VIBESCAPE]: {
        skyTop: new THREE.Color(0x667eea),
        skyHorizon: new THREE.Color(0x764ba2),
        sunColor: new THREE.Color(0xf093fb),
        ambientColor: new THREE.Color(0xc9a5d8),
        groundColor: new THREE.Color(0x7ec896),
        roadColor: new THREE.Color(0x505070),
        roadLineColor: new THREE.Color(0xf093fb),
        terrainColor: new THREE.Color(0x6eb881),
        terrainColor2: new THREE.Color(0x7ec896),
        waterColor: new THREE.Color(0x667eea),
        fogColor: new THREE.Color(0x9370db),
        fogDensity: 0.01,
        timeOfDay: 0.5,
      },
    },
    [Season.SUMMER]: {
      [Mood.CHILL]: {
        skyTop: new THREE.Color(0x4a9eff),
        skyHorizon: new THREE.Color(0x87ceeb),
        sunColor: new THREE.Color(0xffeb3b),
        ambientColor: new THREE.Color(0xfffff0),
        groundColor: new THREE.Color(0xdaa520),
        roadColor: new THREE.Color(0x606060),
        roadLineColor: new THREE.Color(0xffffff),
        terrainColor: new THREE.Color(0xc8b350),
        terrainColor2: new THREE.Color(0xdaa520),
        waterColor: new THREE.Color(0x1e90ff),
        fogColor: new THREE.Color(0xf0e68c),
        fogDensity: 0.006,
        timeOfDay: 0.5,
      },
      [Mood.SUNSET_GLOW]: {
        skyTop: new THREE.Color(0xff4757),
        skyHorizon: new THREE.Color(0xff9068),
        sunColor: new THREE.Color(0xff6b35),
        ambientColor: new THREE.Color(0xffd4a3),
        groundColor: new THREE.Color(0xd4a86a),
        roadColor: new THREE.Color(0x554433),
        roadLineColor: new THREE.Color(0xffd4a3),
        terrainColor: new THREE.Color(0xc89b5a),
        terrainColor2: new THREE.Color(0xd4a86a),
        waterColor: new THREE.Color(0xff6b35).lerp(new THREE.Color(0x1e90ff), 0.4),
        fogColor: new THREE.Color(0xff9068),
        fogDensity: 0.01,
        timeOfDay: 0.8,
      },
      [Mood.NIGHT_DRIVE]: {
        skyTop: new THREE.Color(0x000814),
        skyHorizon: new THREE.Color(0x001d3d),
        sunColor: new THREE.Color(0x8b9cb5),
        ambientColor: new THREE.Color(0x2a3f5f),
        groundColor: new THREE.Color(0x3a3520),
        roadColor: new THREE.Color(0x2a2a2a),
        roadLineColor: new THREE.Color(0xaaaaff),
        terrainColor: new THREE.Color(0x4a4530),
        terrainColor2: new THREE.Color(0x3a3520),
        waterColor: new THREE.Color(0x001d3d),
        fogColor: new THREE.Color(0x001d3d),
        fogDensity: 0.018,
        timeOfDay: 0.95,
      },
      [Mood.STORMY]: {
        skyTop: new THREE.Color(0x3a4556),
        skyHorizon: new THREE.Color(0x6b7a8f),
        sunColor: new THREE.Color(0x9ca9ba),
        ambientColor: new THREE.Color(0x6b7a8f),
        groundColor: new THREE.Color(0x9a8a60),
        roadColor: new THREE.Color(0x404040),
        roadLineColor: new THREE.Color(0xdddddd),
        terrainColor: new THREE.Color(0x9a8560),
        terrainColor2: new THREE.Color(0x9a8a60),
        waterColor: new THREE.Color(0x4a5a6a),
        fogColor: new THREE.Color(0x6b7a8f),
        fogDensity: 0.03,
        timeOfDay: 0.4,
      },
      [Mood.VIBESCAPE]: {
        skyTop: new THREE.Color(0xf093fb),
        skyHorizon: new THREE.Color(0xf5576c),
        sunColor: new THREE.Color(0xffd700),
        ambientColor: new THREE.Color(0xffc4d8),
        groundColor: new THREE.Color(0xe0a858),
        roadColor: new THREE.Color(0x706050),
        roadLineColor: new THREE.Color(0xf093fb),
        terrainColor: new THREE.Color(0xd0a060),
        terrainColor2: new THREE.Color(0xe0a858),
        waterColor: new THREE.Color(0xf5576c),
        fogColor: new THREE.Color(0xffb6c1),
        fogDensity: 0.008,
        timeOfDay: 0.6,
      },
    },
    [Season.AUTUMN]: {
      [Mood.CHILL]: {
        skyTop: new THREE.Color(0x6b8fb5),
        skyHorizon: new THREE.Color(0xa0bcd8),
        sunColor: new THREE.Color(0xffa500),
        ambientColor: new THREE.Color(0xffe4b5),
        groundColor: new THREE.Color(0xcd853f),
        roadColor: new THREE.Color(0x504030),
        roadLineColor: new THREE.Color(0xffffff),
        terrainColor: new THREE.Color(0xb8704f),
        terrainColor2: new THREE.Color(0xcd853f),
        waterColor: new THREE.Color(0x5a7a8a),
        fogColor: new THREE.Color(0xd2b48c),
        fogDensity: 0.012,
        timeOfDay: 0.35,
      },
      [Mood.SUNSET_GLOW]: {
        skyTop: new THREE.Color(0xd84315),
        skyHorizon: new THREE.Color(0xff6f00),
        sunColor: new THREE.Color(0xff5722),
        ambientColor: new THREE.Color(0xffccbc),
        groundColor: new THREE.Color(0xa0522d),
        roadColor: new THREE.Color(0x3a2a1a),
        roadLineColor: new THREE.Color(0xffccbc),
        terrainColor: new THREE.Color(0x8b4513),
        terrainColor2: new THREE.Color(0xa0522d),
        waterColor: new THREE.Color(0xff5722).lerp(new THREE.Color(0x5a7a8a), 0.6),
        fogColor: new THREE.Color(0xff6f00),
        fogDensity: 0.015,
        timeOfDay: 0.78,
      },
      [Mood.NIGHT_DRIVE]: {
        skyTop: new THREE.Color(0x1a0a0f),
        skyHorizon: new THREE.Color(0x2a1a1f),
        sunColor: new THREE.Color(0x7a8a9a),
        ambientColor: new THREE.Color(0x3a2a3a),
        groundColor: new THREE.Color(0x3a2515),
        roadColor: new THREE.Color(0x252525),
        roadLineColor: new THREE.Color(0xbbbbff),
        terrainColor: new THREE.Color(0x4a3525),
        terrainColor2: new THREE.Color(0x3a2515),
        waterColor: new THREE.Color(0x1a2a3a),
        fogColor: new THREE.Color(0x2a1a1f),
        fogDensity: 0.02,
        timeOfDay: 0.08,
      },
      [Mood.STORMY]: {
        skyTop: new THREE.Color(0x2a3540),
        skyHorizon: new THREE.Color(0x5a6a7f),
        sunColor: new THREE.Color(0x8a9aaa),
        ambientColor: new THREE.Color(0x5a6a7f),
        groundColor: new THREE.Color(0x7a5a3a),
        roadColor: new THREE.Color(0x353535),
        roadLineColor: new THREE.Color(0xcccccc),
        terrainColor: new THREE.Color(0x6a4a2a),
        terrainColor2: new THREE.Color(0x7a5a3a),
        waterColor: new THREE.Color(0x3a4a5a),
        fogColor: new THREE.Color(0x5a6a7f),
        fogDensity: 0.028,
        timeOfDay: 0.42,
      },
      [Mood.VIBESCAPE]: {
        skyTop: new THREE.Color(0xfb8b24),
        skyHorizon: new THREE.Color(0xe36414),
        sunColor: new THREE.Color(0xff9f1c),
        ambientColor: new THREE.Color(0xffb627),
        groundColor: new THREE.Color(0xa0603a),
        roadColor: new THREE.Color(0x604030),
        roadLineColor: new THREE.Color(0xffb627),
        terrainColor: new THREE.Color(0x8a502a),
        terrainColor2: new THREE.Color(0xa0603a),
        waterColor: new THREE.Color(0x9a4a2a),
        fogColor: new THREE.Color(0xe36414),
        fogDensity: 0.01,
        timeOfDay: 0.65,
      },
    },
    [Season.WINTER]: {
      [Mood.CHILL]: {
        skyTop: new THREE.Color(0xadd8e6),
        skyHorizon: new THREE.Color(0xe0f2fe),
        sunColor: new THREE.Color(0xfffacd),
        ambientColor: new THREE.Color(0xf0f8ff),
        groundColor: new THREE.Color(0xe8e8f8),
        roadColor: new THREE.Color(0x606078),
        roadLineColor: new THREE.Color(0xffffff),
        terrainColor: new THREE.Color(0xe0e8f8),
        terrainColor2: new THREE.Color(0xe8e8f8),
        waterColor: new THREE.Color(0x7ac5cd),
        fogColor: new THREE.Color(0xe0f2fe),
        fogDensity: 0.015,
        timeOfDay: 0.38,
      },
      [Mood.SUNSET_GLOW]: {
        skyTop: new THREE.Color(0xffb6c1),
        skyHorizon: new THREE.Color(0xffc8dd),
        sunColor: new THREE.Color(0xffafcc),
        ambientColor: new THREE.Color(0xffd4e5),
        groundColor: new THREE.Color(0xd8d8e8),
        roadColor: new THREE.Color(0x505070),
        roadLineColor: new THREE.Color(0xffe5ec),
        terrainColor: new THREE.Color(0xd0d8e8),
        terrainColor2: new THREE.Color(0xd8d8e8),
        waterColor: new THREE.Color(0xffb6c1).lerp(new THREE.Color(0x7ac5cd), 0.5),
        fogColor: new THREE.Color(0xffc8dd),
        fogDensity: 0.018,
        timeOfDay: 0.82,
      },
      [Mood.NIGHT_DRIVE]: {
        skyTop: new THREE.Color(0x0f1419),
        skyHorizon: new THREE.Color(0x1f2429),
        sunColor: new THREE.Color(0x8a9aaa),
        ambientColor: new THREE.Color(0x2a3a4a),
        groundColor: new THREE.Color(0xc8c8d8),
        roadColor: new THREE.Color(0x353545),
        roadLineColor: new THREE.Color(0xccccff),
        terrainColor: new THREE.Color(0xc0c8d8),
        terrainColor2: new THREE.Color(0xc8c8d8),
        waterColor: new THREE.Color(0x1a2a3a),
        fogColor: new THREE.Color(0x1f2429),
        fogDensity: 0.022,
        timeOfDay: 0.1,
      },
      [Mood.STORMY]: {
        skyTop: new THREE.Color(0x3a4550),
        skyHorizon: new THREE.Color(0x6a7a8f),
        sunColor: new THREE.Color(0x9aabb8),
        ambientColor: new THREE.Color(0x6a7a8f),
        groundColor: new THREE.Color(0xb8b8c8),
        roadColor: new THREE.Color(0x404050),
        roadLineColor: new THREE.Color(0xdddddd),
        terrainColor: new THREE.Color(0xb0b8c8),
        terrainColor2: new THREE.Color(0xb8b8c8),
        waterColor: new THREE.Color(0x4a5a6a),
        fogColor: new THREE.Color(0x6a7a8f),
        fogDensity: 0.032,
        timeOfDay: 0.43,
      },
      [Mood.VIBESCAPE]: {
        skyTop: new THREE.Color(0x00d9ff),
        skyHorizon: new THREE.Color(0x7bffff),
        sunColor: new THREE.Color(0x00ffff),
        ambientColor: new THREE.Color(0xccffff),
        groundColor: new THREE.Color(0xe0e8ff),
        roadColor: new THREE.Color(0x707088),
        roadLineColor: new THREE.Color(0x00ffff),
        terrainColor: new THREE.Color(0xd8e8ff),
        terrainColor2: new THREE.Color(0xe0e8ff),
        waterColor: new THREE.Color(0x00d9ff),
        fogColor: new THREE.Color(0xaae5ff),
        fogDensity: 0.012,
        timeOfDay: 0.55,
      },
    },
  };

  static get(season: Season, mood: Mood): PaletteColors {
    return this.palettes[season][mood];
  }

  static lerp(a: PaletteColors, b: PaletteColors, t: number): PaletteColors {
    return {
      skyTop: new THREE.Color().lerpColors(a.skyTop, b.skyTop, t),
      skyHorizon: new THREE.Color().lerpColors(a.skyHorizon, b.skyHorizon, t),
      sunColor: new THREE.Color().lerpColors(a.sunColor, b.sunColor, t),
      ambientColor: new THREE.Color().lerpColors(a.ambientColor, b.ambientColor, t),
      groundColor: new THREE.Color().lerpColors(a.groundColor, b.groundColor, t),
      roadColor: new THREE.Color().lerpColors(a.roadColor, b.roadColor, t),
      roadLineColor: new THREE.Color().lerpColors(a.roadLineColor, b.roadLineColor, t),
      terrainColor: new THREE.Color().lerpColors(a.terrainColor, b.terrainColor, t),
      terrainColor2: new THREE.Color().lerpColors(a.terrainColor2, b.terrainColor2, t),
      waterColor: new THREE.Color().lerpColors(a.waterColor, b.waterColor, t),
      fogColor: new THREE.Color().lerpColors(a.fogColor, b.fogColor, t),
      fogDensity: a.fogDensity + (b.fogDensity - a.fogDensity) * t,
      timeOfDay: a.timeOfDay + (b.timeOfDay - a.timeOfDay) * t,
    };
  }
}
